### PR TITLE
Fix #9

### LINKED ISSUE #9: Recipes don't get send to the client with FTBTweaks
hey,
adding recipes only on the server doesn't sync it to the client. Running /mt reload will show the recipes until the player relogs.
I tried it with those directories:
- scripts
- world/scripts
- modpack/common/scripts
- modpack/normal/scripts

### PR DESCRIPTION
**Pull request by phit**
This is my proposed solution for #9, I tested this myself and didn't see any issue with it. Functionality for singleplayer is unchanged, if the player is playing on a dedicated server the scripts are handled by the server. For more details see my post in the issue. This won't cause any new load on the client when connecting to a server, since currently the client already receives all scripts from the server.

Both `/ftb reload` and `/mt reload` still work as expected!

### CODE REVIEW

**Comment by jaredlll08** [comment]
Can you do me a favor and test a JEI script, like add a crafting recipe and make sure it pops up on the client

**Comment by phit** [comment]
I did test adding and removing of recipes in singleplayer and on a dedicated server, in both cases JEI is updated correctly even when reloading with the commands mentioned above!

**Comment by jaredlll08** [comment]
Can you test is something like localization works? since that is a clientside only thing iirc

**Comment by phit** [comment]
Yeah, can do. I'll also do stuff like tooltips, but from my understanding it shouldn't matter since the raw script is just send to the client and then executed there.

**Comment by jaredlll08** [comment]
I'm just making sure, since it would be nice to get this finally fixed

**Comment by phit** [comment]
Yup, works http://i.imgur.com/cLxp8NI.png

All the other ones that are in the script from that screenshot work too, with the script only on the server!

**Comment by phit** [comment]
any update on this?

**Comment by jaredlll08** [comment]
I totally forgot about this, sorry

**Comment by phit** [comment]
No problem, just happy to know this will be fixed in the future!

**Pull request merged**
