### PR TITLE
fixed #1

### LINKED ISSUE #1: world/scripts doesn't get loaded
hey, 

it seems that the scripts in the world folder don't get loaded if FTBTweaks is installed.
Would be great if this gets fixed as we need it to send recipes from the server to the client.

Edit: Same issue with the scripts folder in the main folder.

### PR DESCRIPTION
**Pull request by dries007**
Also fixed dependency information not being used.

### CODE REVIEW

**Comment by jaredlll08** [comment]
May I ask what the useMetadata = false does?

**Comment by dries007** [comment]
The "dependencies = ..." string doesn't get used unless that is set, its a flaw in the FML code.

**Comment by jaredlll08** [comment]
Hmm I have never had that problem, I'll merge this in the morning, when I can look over it

**Comment by dries007** [comment]
It didn't used to be an issue, until there was a change in the FML code a while ago. Now, even thought it sais that is defaults to false, it actually only counts if you set it manually. I don't think a different load order would actually be an issue in this particular case, but you should put it there in case that ever changed. It took me a couple of hours to figure out and I'd like to save other people that headache.

**Comment by jaredlll08** [comment]
Could you please update your code to the latest, it is a mission to merge with conflicts >_<

**Comment by dries007** [comment]
Sure

**Comment by dries007** [comment]
Done, I just merged it on my side and manually patched the issue since this only the one line. :smile: 
Don't forget to test before you put this in packs, I didn't get the chance to do more then a small local test.

**Pull request merged**
